<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningLevel>0</WarningLevel>
    <AnalysisLevel>none</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WinInteropUtils.WinForms" Version="0.24.0-beta" />
  </ItemGroup>

</Project>